id: P691B436D
initial_creation_type: ocr
source_metadata:
  volumes:
    d30da6dc661d428cb7320ab2198c5874:
      base_file: v063.txt
      image_group_id: I1PD95908
      title: ལྟ་བ་ཐ་དད་པ་རྣམ་པར་ཕྱེ་བ་མདོར་བསྡུས་པ།
      total_pages: 1926
      volume_number: 63
